
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/pw0/scoop/apps/cmake/current/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
